labels:
  0: 'person'
  1: 'bicycle'
  2: 'car'
  3: 'motorcycle'
  4: 'train'
  5: 'truck'
  6: 'boat'
  7: 'bridge'
  8: 'building-other-merged'
  9: 'gravel'
  10: 'railroad'
  11: 'road'
  12: 'pavement-merged'
  13: 'dirt-merged'
  14: 'sand'
  15: 'snow'
  16: 'floor-other-merged'
  17: 'grass-merged'
  18: 'wall-other-merged'
  19: 'rock-merged'
  20: 'water-other'
  21: 'tree-merged'
  22: 'fence-merged'
  23: 'sky-other-merged'
  24: 'floor-concrete'
  25: 'container'
  26: 'self-arm'
  27: 'self-leg'
  28: 'stone'
  29: 'gravel-pile'
  30: 'sand-pile'
  31: 'unknown'
  32: 'unknown2'
learning_map:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
  9: 9
  10: 10
  11: 11
  12: 12
  13: 13
  14: 14
  15: 15
  16: 16
  17: 17
  18: 18
  19: 19
  20: 20
  21: 21
  22: 22
  23: 23
  24: 24
  25: 25
  26: 26
  27: 27
  28: 28
  29: 29
  30: 30
  31: 31
  32: 32
learning_map_inv:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
  9: 9
  10: 10
  11: 11
  12: 12
  13: 13
  14: 14
  15: 15
  16: 16
  17: 17
  18: 18
  19: 19
  20: 20
  21: 21
  22: 22
  23: 23
  24: 24
  25: 25
  26: 26
  27: 27
  28: 28
  29: 29
  30: 30
  31: 31
  32: 32
split: # sequence numbers
  train:
    - 0
  valid:
    - 0
  test:
    - 0