labels:
  0: 'person'
  1: 'bicycle'
  2: 'car'
  3: 'motorcycle'
  4: 'train'
  5: 'truck'
  6: 'boat'
  7: 'bridge'
  8: 'building-other-merged'
  9: 'gravel'
  10: 'railroad'
  11: 'road'
  12: 'pavement-merged'
  13: 'dirt-merged'
  14: 'sand'
  15: 'snow'
  16: 'floor-other-merged'
  17: 'grass-merged'
  18: 'wall-other-merged'
  19: 'rock-merged'
  20: 'water-other'
  21: 'tree-merged'
  22: 'fence-merged'
  23: 'sky-other-merged'
  24: 'floor-concrete'
  25: 'container'
  26: 'self-arm'
  27: 'self-leg'
  28: 'stone'
  29: 'gravel-pile'
  30: 'sand-pile'
  31: 'unknown'
  32: 'unknown2'
labels_9:
  0: 'unlabeled'
  1: 'person'
  2: 'vehicle'
  3: 'building-other-merged'
  4: 'floor-other-merged'
  5: 'rock-merged'
  6: 'water-other'
  7: 'tree-merged'
  8: 'stone'
  9: 'pile-other-merged'
learning_map:
  0: 1
  1: 2
  2: 2
  3: 2
  4: 2
  5: 2
  6: 2
  7: 3
  8: 3
  9: 4
  10: 4
  11: 4
  12: 4
  13: 4
  14: 4
  15: 4
  16: 4
  17: 4
  18: 3
  19: 5
  20: 6
  21: 7
  22: 2
  23: 0
  24: 4
  25: 3
  26: 0
  27: 0
  28: 8
  29: 9
  30: 9
  31: 0
  32: 0
learning_map_inv:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
  9: 9
learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "person"
  2: False     # "vehicle"
  3: False     # "building-other-merged"
  4: False     # "floor-other-merged"
  5: False     # "rock-merged"
  6: False     # "water-other"
  7: False     # "tree-merged"
  8: False     # "stone"
  9: False     # "pile-other-merged"
split: # sequence numbers
  train:
    - 0
  valid:
    - 0
  test:
    - 0
color_map: # bgr
  0 : [0, 0, 0]
  1 : [220, 20, 60]
  2: [0, 0, 142]
  3: [248, 231, 28]
  4: [124, 74, 181]
  5: [0, 114, 143]
  6: [58, 71, 149]
  7: [107, 142, 35]
  8: [0, 114, 113]
  9: [124, 74, 141]
  10: [200, 40, 255]
  11: [90, 30, 150]
  12: [255, 0, 255]
  13: [255, 150, 255]
  14: [75, 0, 75]
  15: [75, 0, 175]
  16: [0, 200, 255]
  17: [50, 120, 255]
  18: [0, 150, 255]
  19: [170, 255, 150]
  20: [0, 175, 0]
  21: [0, 60, 135]
  22: [80, 240, 150]
  23: [150, 240, 255]
  25: [0, 0, 255]
  26: [255, 255, 50]
  27: [245, 150, 100]
  28: [255, 0, 0]
  29: [200, 40, 255]
  30: [30, 30, 255]
  31: [90, 30, 150]
  32: [0, 0, 0]